void IF97cpp_if97_initiate();
double IF97cpp_t_ph (double p, double h);
double IF97cpp_t_ps (double p, double s);
double IF97cpp_v_pt (double p, double t);
double IF97cpp_v_ph (double p, double h);
double IF97cpp_v_ps (double p, double s);
double IF97cpp_h_pt (double p, double t);
double IF97cpp_h_ps (double p, double s);
double IF97cpp_h_ps_meta (double p, double s);
double IF97cpp_s_pt (double p, double t);
double IF97cpp_s_ph (double p, double h);
double IF97cpp_w_pt (double p, double t);
double IF97cpp_w_ph (double p, double h);
double IF97cpp_w_ps (double p, double s);
double IF97cpp_cppt (double p, double t);
double IF97cpp_cpph (double p, double h);
double IF97cpp_cpps (double p, double s);
double IF97cpp_cvpt (double p, double t);
double IF97cpp_cvph (double p, double h);
double IF97cpp_cvps (double p, double s);
double IF97cpp_p_vt (double v, double t);
double IF97cpp_p_ts (double t, double s);
double IF97cpp_p_hs (double h, double s);
double IF97cpp_p_hs_meta (double h, double s);
double IF97cpp_p_vh (double v, double h);
double IF97cpp_p_vs (double v, double s);
double IF97cpp_v_ts (double t, double s);
double IF97cpp_h_vt (double v, double t);
double IF97cpp_h_ts (double t, double s);
double IF97cpp_h_vs (double v, double s);
double IF97cpp_s_vt (double v, double t);
double IF97cpp_w_vt (double v, double t);
double IF97cpp_cpvt (double v, double t);
double IF97cpp_cvvt (double v, double t);
double IF97cpp_p_th (double t, double h);
double IF97cpp_h_pv (double p, double v);
double IF97cpp_s_pv (double p, double v);
double IF97cpp_t_hx (double h, double x);
double IF97cpp_t_sx (double s, double x);
int IF97cpp_region_pt (double p, double t);
int IF97cpp_region_ph (double p, double h);		
int IF97cpp_region_ps (double p, double s);		
int IF97cpp_region_hs (double h, double s);		
int IF97cpp_region_ph_meta (double p, double h); 
int IF97cpp_region_ps_meta (double p, double s); 
double IF97cpp_p_sat_t (double t);
double IF97cpp_t_sat_p (double p);
double IF97cpp_v_lsat_p (double p);
double IF97cpp_h_lsat_p (double p);
double IF97cpp_s_lsat_p (double p);
double IF97cpp_w_lsat_p (double p);
double IF97cpp_cplsat_p (double p);
double IF97cpp_cvlsat_p (double p);
double IF97cpp_v_gsat_p (double p);
double IF97cpp_h_gsat_p (double p);
double IF97cpp_s_gsat_p (double p);
double IF97cpp_w_gsat_p (double p);
double IF97cpp_cpgsat_p (double p);
double IF97cpp_cvgsat_p (double p);
double IF97cpp_v_xt (double x, double t);
double IF97cpp_h_xt (double x, double t);
double IF97cpp_s_xt (double x, double t);
double IF97cpp_w_xt (double x, double t);
double IF97cpp_cpxt (double x, double t);
double IF97cpp_cvxt (double x, double t);
double IF97cpp_v_xp (double x, double p);
double IF97cpp_h_xp (double x, double p);
double IF97cpp_s_xp (double x, double p);
double IF97cpp_w_xp (double x, double p);
double IF97cpp_cpxp (double x, double p);
double IF97cpp_cvxp (double x, double p);
double IF97cpp_x_pt (double p, double t);
double IF97cpp_x_ph (double p, double h);
double IF97cpp_x_ps (double p, double s);
double IF97cpp_dynamic_viscosity_tvp (double t, double v, double p);
double IF97cpp_dynamic_viscosity_pt (double p, double t);
double IF97cpp_dynamic_viscosity_ph (double p, double h);
double IF97cpp_dynamic_viscosity_ps (double p, double s); 
double IF97cpp_kinematic_viscosity_tvp (double t, double v, double p);
double IF97cpp_kinematic_viscosity_pt (double p, double t);
double IF97cpp_kinematic_viscosity_ph (double p, double h);
double IF97cpp_kinematic_viscosity_ps (double p, double s);
double IF97cpp_u_lsat_p (double p);
double IF97cpp_u_gsat_p (double p);
double IF97cpp_u_lsat_t (double t);
double IF97cpp_u_gsat_t (double t);
double IF97cpp_u_pt (double p, double t);
double IF97cpp_u_ph (double p, double h);
double IF97cpp_u_ps (double p, double s);
double IF97cpp_thermal_conductivity_tvp (double t, double v, double p);
double IF97cpp_thermal_conductivity_pt (double p, double t);
double IF97cpp_thermal_conductivity_ph (double p, double h);
double IF97cpp_thermal_conductivity_ps (double p, double s);
double IF97cpp_isentropic_coefficient_pt (double p, double t);
double IF97cpp_isentropic_coefficient_ph (double p, double h);
double IF97cpp_isentropic_coefficient_ps (double p, double s);
double IF97cpp_isentropic_coefficient_vt (double v, double t);
double IF97cpp_isentropic_coefficient_xt (double x, double t);
double IF97cpp_isentropic_coefficient_xp (double x, double p);
double IF97cpp_isentropic_coefficient_lsat_p (double p);
double IF97cpp_isentropic_coefficient_gsat_p (double p);
double IF97cpp_surface_tension_t (double t);
