function BLADE = get_blade_from_mat(name_of_matfile)
% BastlMaster 333.3.6 (c) Všechna káva vypražena
% 16.7.2015
%
% 

    RAD_ID = 1;
    MI_ID = 2;
    XMIN_ID = 3;
    XMAX_ID = 4;

    %SERVICEPATH='C:\Data\bld_dev\BladeMaster.3.4.0\matlab\lib_out';

    BLADE.bladeCount = [];
    BLADE.hubDiameter = [];
    BLADE.sParameters = [];
    BLADE.sLeadingPoint = [];
    BLADE.hubParam = [];
    BLADE.shroudParam = [];
    BLADE.LEAN_LIMITS = [];
    BLADE.LEAN = [];
    BLADE.SWEEP_LIMITS = [];
    BLADE.SWEEP = [];
    BLADE.misesMesh = [];
    BLADE.misesBC = [];
    BLADE.stackingPoint = '';
    
    %addpath(SERVICEPATH);
    [ BLADE.bladeCount,...
      BLADE.hubDiameter,...
      BLADE.sParameters,...
      BLADE.sLeadingPoint, ...
      BLADE.hubParam,...
      BLADE.shroudParam,...
      BLADE.LEAN_LIMITS,...
      BLADE.LEAN,...
      BLADE.SWEEP_LIMITS, ...
      BLADE.SWEEP,...
      BLADE.misesMesh,...
      BLADE.misesBC,...
      BLADE.stacking ] = import_matlab(name_of_matfile);

      switch BLADE.stacking
        case 0
            BLADE.stackingPoint = 'cg';
        case 1
            BLADE.stackingPoint = 'te';
        case 2
            BLADE.stackingPoint = 'lp';
        otherwise
            BLADE.stackingPoint = '';
      end
  
  
      %SERVICEPATH='C:\Data\bld_dev\BladeMaster.3.4.0\matlab\lib_geom;C:\Data\bld_dev\BladeMaster.3.4.0\matlab\lib_3d';
      %addpath(SERVICEPATH);
      
      [BLADE.XY_2D, BLADE.GIndex2D] = generate_2D(BLADE.hubDiameter,...
                                                  BLADE.sParameters,...
                                                  BLADE.sLeadingPoint);
      
      BLADE.SIDEWALL = [ BLADE.hubDiameter,...
                         (BLADE.shroudParam(RAD_ID)-(BLADE.hubDiameter)/2),...                      %(BLADE.shroudParam(RAD_ID)-BLADE.hubParam(RAD_ID)),...
                         BLADE.hubParam(MI_ID),...
                         BLADE.shroudParam(MI_ID), ];

               
      [BLADE.XYZ_3D, BLADE.SC] = generate_3d(BLADE.XY_2D,...
                                             BLADE.SIDEWALL,...
                                             BLADE.LEAN_LIMITS,...
                                             BLADE.LEAN,...
                                             BLADE.SWEEP_LIMITS,...
                                             BLADE.SWEEP);
      
      %Generate hub and shroud curve
      [BLADE.HUB, BLADE.SHROUD] = generate_hs( BLADE.SIDEWALL,...
                                               BLADE.SC,...
                                               BLADE.hubParam(XMIN_ID),...
                                               BLADE.hubParam(XMAX_ID),...
                                               BLADE.shroudParam(XMIN_ID),...
                                               BLADE.shroudParam(XMAX_ID) );
  
    return;
end